command_timeout = 1000

palette = "custom"


"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

# $os âœ\
format = """
$os\
$directory\
$fill\
${custom.giturl}\
$git_branch\
$git_state\
$git_status\
$python\
$elixir\
$erlang\
$dart\
$lua\
$php\
$nodejs\
${custom.typescript}\
$golang\
$haskell\
$kotlin\
$java\
$swift\
$rust\
$ruby\
${custom.docker}\
${custom.yarn}\
${custom.pnpm}\
$bun\
$package\
$aws\
$cmd_duration\
$line_break\
$time\
$character"""


[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ïŒ‚"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"


[fill]
symbol = " "  
style = "none" 

[username]
# show_always = true
# style_user = "bg:surface0 fg:text"
# style_root = "bg:surface0 fg:text"
# format = '[ $user ]($style)'

[directory]
style = "fg:#000000 bg:#72849B"
format = "[î‚´](#ffffff)[î‚¶](#72849B)[ $path ]($style)[î‚´](#72849B)"
truncation_length = 2
truncation_symbol = 'ï€• / ' #../
truncate_to_repo = false


[directory.substitutions]
"~" = "ï€• " 
".dotfiles" ="î«¬ "
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ï’‰ "


[os]
# symbol = "ï…¹ " 
style = "fg:#000000 bg:#ffffff"
format = "[î‚¶](#ffffff)[ $symbol ]($style )"
disabled = false

#ZSH
# [custom.giturl]
# description = "Display symbol for remote Git server"
# command = """
# GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
# if [[ "$GIT_REMOTE" =~ "github" ]]; then
#     GIT_REMOTE_SYMBOL="ïˆ "
# elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
#     GIT_REMOTE_SYMBOL="ïŠ– "
# elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
#     GIT_REMOTE_SYMBOL="ï…± "
# elif [[ "$GIT_REMOTE" =~ "git" ]]; then
#     GIT_REMOTE_SYMBOL="ï¡ "
# else
#     GIT_REMOTE_SYMBOL="îª„ " 
# fi
# echo "$GIT_REMOTE_SYMBOL "
# """
# when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
# format = "$output"

#FISH
[custom.giturl]
description = "Display symbol for remote Git server"
command = """
set GIT_REMOTE (git ls-remote --get-url 2> /dev/null)

if string match -q "*github*" $GIT_REMOTE
    set GIT_REMOTE_SYMBOL "ïˆ "
else if string match -q "*gitlab*" $GIT_REMOTE
    set GIT_REMOTE_SYMBOL "ïŠ– "
else if string match -q "*bitbucket*" $GIT_REMOTE
    set GIT_REMOTE_SYMBOL "ï…± "
else if string match -q "*git*" $GIT_REMOTE
    set GIT_REMOTE_SYMBOL "ï¡ "
else
    set GIT_REMOTE_SYMBOL "îª„ "
end

echo $GIT_REMOTE_SYMBOL
"""
when = "git rev-parse --is-inside-work-tree 2> /dev/null"
format = "$output"


[git_branch]
symbol = "[î‚¶](#090909)ï˜ "
style = "fg:white bg:#090909"
format =  ' [$symbol$branch]($style)[î‚´](#090909)'


# [git_branch]
# style = 'fg:white'
# symbol = 'ï˜ '
# format = ' [on] [$symbol$branch ]($style)'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '


[git_status]
conflicted = '[ï± (#FF0000)]'
ahead = '[â¬† \($count\)](#ffffff)'  
behind = '[â¬‡ \($count\)](#8A2BE2)'
diverged = '[ï‘€ ](#FF4500)'
up_to_date = '[âœ”](#cacaca)'
untracked = '[ï  \($count\)](#3CBDFF)' 
stashed = '[ó°•” \($count\)](#D69CFF)'
modified = '[ï„ \($count\)](#85FCF9)'  
staged = '[ï‘— \($count\)](#B3F8C5)'
renamed = '[ó°‘• ](#8A2BE2)'
deleted = '[ï‘˜ \($count\)](#FFC4C0)'


# [git_status]
# format = ' [($all_status$ahead_behind )]($style)'


[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = "îŒ½ "

[lua]
symbol = 'î˜  '
format = ' [ $symbol( $version) ]($style)'


[dart]
symbol = 'î˜ '
format = '[ $symbol( $version) ]($style)'

[elixir]
symbol = 'î˜­ '
format = '[ $symbol( $version) ]($style)'

[erlang]
symbol = 'î± '
format = '[ $symbol( $version) ]($style)'


[nodejs]
style = "fg:#00FC71 bg:#111111"
symbol = 'î´ '
format = "[î‚¶](#111111)[ $symbol($version) ]($style)[î‚´](#111111)"
detect_extensions = ["js", "mjs", "cjs","jsx", "ts", "tsx"]
detect_files = ["package.json", "node_modules"]


[custom.pnpm]
style = "bold #FFC4C0"
symbol = 'î¡¥ '
format = '(#52676B)[ $symbol( $version) ]($style)'

[custom.yarn]
style = "bold #2e8b57"
symbol = 'îš§ '
format = '[ $symbol( $version) ]($style)'

[bun]
style = "fg:#EDDBD0 bg:#111111"
symbol = "î¯ "
format = "[î‚¶](#111111)[ $symbol($version) ]($style)[î‚´](#111111)"

[package]
style = "fg:#8B4513 bg:#111111"
symbol = 'ï’‡ '
format = "[î‚¶](#111111)[ $symbol($version) ]($style)[î‚´](#111111)"


[custom.typescript]
style = "bold #007ACC"  
symbol = "î˜¨ " 
format = '[$symbol($version) ]($style)'
detect_extensions = ["ts", "tsx"]


[c]
symbol = "î˜ "
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = "î¨ "
format = '[ $symbol( $version) ]($style)'

[golang]
style = "fg:#00C1FF bg:#111111"
symbol = 'î˜§ '
format = "[î‚¶](#111111)[ $symbol($version) ]($style)[î‚´](#111111)"

[php]
style = "fg:#AFAFFF bg:#111111"
symbol = "î˜ˆ "
format = "[î‚¶](#111111)[ $symbol($version) ]($style)[î‚´](#111111)"

[java]
style = "fg:#EC7063 bg:#111111"
symbol = "î¶¯ "
format = "[î‚¶](#111111)[ $symbol($version) ]($style)[î‚´](#111111)"


[kotlin]
symbol = "î˜´ "
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = "î˜Ÿ "
format = '[ $symbol( $version) ]($style)'

[ruby]
style = "fg:#E0115F bg:#111111"
symbol = 'îˆ '
format = "[î‚¶](#111111)[ $symbol($version) ]($style)[î‚´](#111111)"



[python]
style = "fg:#F1CA81 bg:#111111"
symbol = 'îˆµ '
format = '[î‚¶](#111111)[ ${symbol}${asdf_prefix}( ${version} )(\($virtualenv\) )]($style)[î‚´](#111111)'

# pyenv_version_name = true
# pyenv_prefix = ''


[swift]
style = "fg:#FF6B83 bg:#111111"
symbol = "î• "
format = "[î‚¶](#111111)[ $symbol($version) ]($style)[î‚´](#111111)"

[docker_context]
# symbol = 'ïŒˆ '
symbol = ' ğŸ³ '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[custom.docker]
disabled = false
symbol = 'ğŸ³ '
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']



[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[ $duration]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:peach"
format = '[[ ïº $time ](fg:white bg:foam)]($style)'

[env_var]
symbol = "[â•­â•´](bold fg:white)"
variable = 'SHELL'
format = "$symbol"
disabled = false

[line_break]
disabled = false


[character]
disabled = false
success_symbol = '[âœ](bold fg:white)' # âœ â¯
error_symbol = '[âœ˜](bold fg:red)'
# success_symbol = '[â•°â¯ï„…](bold fg:white)'
# error_symbol = '[â•°â¯ï„…](bold fg:red)'
vimcmd_symbol = '[ï´](bold fg:purple)'
vimcmd_replace_one_symbol = '[ï´](bold fg:purple)'
vimcmd_replace_symbol = '[ï´](bold fg:purple)'
vimcmd_visual_symbol = '[ï´](bold fg:lavender)'


#palettes

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "purple"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white='#D8DEE9'


[palettes.dracula]
sapphire = "#bd93f9"
blue = "#89b4fa"
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#BF616A"
yellow = "#f1fa8c"

[palettes.custom]
sapphire = "#bd93f9"
blue = "#89b4fa"
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = '#50fa7b'
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = 'gray'
yellow = "#f1fa8c"


