command_timeout = 1000

palette = "custom"


"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

# $os âœ\
format = """
$username\
$directory\
$fill\
${custom.giturl}\
$git_branch\
$git_state\
$git_status\
$python\
$elixir\
$dart\
$lua\
$php\
$nodejs\
${custom.typescript}\
$golang\
$haskell\
$kotlin\
$java\
$swift\
$rust\
$ruby\
${custom.podman_version}\
${custom.docker_version}\
${custom.yarn}\
${custom.pnpm}\
$bun\
$package\
$aws\
$cmd_duration\
$line_break\
$time\
$character"""


[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ïŒ‚"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

# â”â”
[fill]
symbol = " â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€"
style = "#52676B" 

[username]
show_always = true
style_user = "bold #ffffff"
style_root = "bold #ffffff"
format = '[ï€‡](#ffffff)[ $user ]($style)'


[directory]
style = "bold #72879D"   #72879D #c18efe
# format = "in î—¾ [$path ]($style)"
format = "[in](#52676B) [î—¾ $path]($style)"
truncation_length = 2
truncation_symbol = '' #../
truncate_to_repo = false




[directory.substitutions]

"~" = "Root" 
".dotfiles" ="Dotfiles"
# "Documents" = "ó°ˆ™ "
# "Downloads" = "ï€™ "
# "Music" = "ó°š "
# "Pictures" = "ï€¾ "
# "Developer" = "ï’‰ "


[os]
# symbol = "  ï…¹  " 
# style = "fg:white bg:#090909"
# format = "[î‚¶](#090909)[$symbol]($style)[î‚´](#090909)"
disabled = false

#ZSH
# [custom.giturl]
# description = "Display symbol for remote Git server"
# command = """
# GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
# if [[ "$GIT_REMOTE" =~ "github" ]]; then
#     GIT_REMOTE_SYMBOL="ïˆ "
# elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
#     GIT_REMOTE_SYMBOL="ïŠ– "
# elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
#     GIT_REMOTE_SYMBOL="ï…± "
# elif [[ "$GIT_REMOTE" =~ "git" ]]; then
#     GIT_REMOTE_SYMBOL="ï¡ "
# else
#     GIT_REMOTE_SYMBOL="îª„ " 
# fi
# echo "$GIT_REMOTE_SYMBOL "
# """
# when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
# format = "$output"

#FISH
[custom.giturl]
description = "Display symbol for remote Git server"
command = """
set GIT_REMOTE (git ls-remote --get-url 2> /dev/null)

if string match -q "*github*" $GIT_REMOTE
    set GIT_REMOTE_SYMBOL "ïˆ "
else if string match -q "*gitlab*" $GIT_REMOTE
    set GIT_REMOTE_SYMBOL "ïŠ– "
else if string match -q "*bitbucket*" $GIT_REMOTE
    set GIT_REMOTE_SYMBOL "ï…± "
else if string match -q "*git*" $GIT_REMOTE
    set GIT_REMOTE_SYMBOL "ï¡ "
else
    set GIT_REMOTE_SYMBOL "îª„ "
end

echo $GIT_REMOTE_SYMBOL
"""
when = "git rev-parse --is-inside-work-tree 2> /dev/null"
format = "$output"


[git_branch]
symbol = "[î‚¶](#090909)ï˜ "
style = "fg:white bg:#090909"
format =  ' [$symbol$branch]($style)[î‚´](#090909)'


# [git_branch]
# style = 'fg:white'
# symbol = 'ï˜ '
# format = ' [on] [$symbol$branch ]($style)'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '


[git_status]
conflicted = '[ï± (#FF0000)]'
ahead = '[â¬† \($count\)](#ffffff)'  
behind = '[â¬‡ \($count\)](#8A2BE2)'
diverged = '[ï‘€ ](#FF4500)'
up_to_date = '[âœ”](#cacaca)'
untracked = '[ï  \($count\)](#3CBDFF)' 
stashed = '[ó°•” \($count\)](#D69CFF)'
modified = '[ï„ \($count\)](#85FCF9)'  
staged = '[ï‘— \($count\)](#B3F8C5)'
renamed = '[ó°‘• ](#8A2BE2)'
deleted = '[ï‘˜ \($count\)](#FFC4C0)'


# [git_status]
# format = ' [($all_status$ahead_behind )]($style)'


[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = "îŒ½ "

[lua]
symbol = 'î˜  '
format = '[via](#52676b) [ $symbol( $version) ]($style)'


[dart]
symbol = 'î˜ '
format = '[via](#52676b)[ $symbol( $version) ]($style)'

[elixir]
symbol = 'î˜­ '
format = '[ $symbol( $version) ]($style)'
detect_extensions = ['ex', 'exs']
detect_files = ['mix.exs']

[erlang]
symbol = 'î± '
format = '[ $symbol( $version) ]($style)'
detect_extensions = ['erl', 'hrl']
detect_files = ['rebar.config', 'erlang.mk']


[nodejs]
symbol = 'î´ '
format = '[$symbol( $version) ]($style)'
detect_extensions = ["js", "mjs", "cjs","jsx", "ts", "tsx"]
detect_files = ["package.json", "node_modules"]

[custom.pnpm]
style = "bold #FFC4C0"
symbol = 'î¡¥ '
format = '[via](#52676B)[ $symbol( $version) ]($style)'

[custom.yarn]
style = "bold #2e8b57"
symbol = 'îš§ '
format = '[via](#52676B)[ $symbol( $version) ]($style)'

[bun]
style = "bold #EDDBD0"
symbol = 'î¯ '
format = '[via](#52676B)[ $symbol( $version) ]($style)'

[package]
style = "bold #8B4513"
symbol = 'ï’‡ '
format = '[via](#52676B)[ $symbol( $version) ]($style)'


[custom.typescript]
style = "bold #007ACC"  
symbol = "î˜¨ " 
format = '[$symbol($version) ]($style)'
detect_extensions = ["ts", "tsx"]


[c]
symbol = "î˜ "
format = '[via](#52676b)[[ $symbol( $version) ]]($style)'

[rust]
symbol = "î¨ "
format = '[via](#52676b)[[ $symbol( $version) ]]($style)'

[golang]
symbol = "î™ " #î™  î˜§
format = '[via](#52676b)[ $symbol( $version) ]($style)'
detect_files = ["go.mod"]

[php]
symbol = "î˜ˆ "
format = '[via](#52676b)[ $symbol( $version) ]($style)'

[java]
style = "fg:#EC7063"
symbol = "î¶¯ "
format = '[ $symbol( $version) ]($style)'


[kotlin]
symbol = "î˜´ "
format = '[via](#52676b)[[ $symbol( $version) ]]($style)'

[haskell]
symbol = "î˜Ÿ "
format = '[via](#52676b)[[ $symbol( $version) ]]($style)'

[ruby]
style = "fg:#E0115F"
symbol = 'îˆ '
format = '[via](#52676b)[[ $symbol( $version) ]]($style)'



[python]
symbol = 'îˆµ '
style = "fg:#F1CA81"
format = '[via](#52676B)[ ${symbol}${asdf_prefix}( ${version} )(\($virtualenv\) )]($style)'
# pyenv_version_name = true
# pyenv_prefix = ''

[swift]
symbol = 'î• '
format = '[via](#52676b)[[ $symbol( $version) ]]($style)'



[custom.docker_version]
style = 'fg:#019CFE'
command = "docker --version | cut -d ' ' -f3 | tr -d ','"
detect_files = ["Dockerfile", "docker-compose.yml", "docker-compose.yaml"]
format = "[[via](#52676B) ïˆŸ  $output]($style) "

[custom.podman_version]
style = 'fg:#8E44AD'
symbol = 'ó°Œ½ '  
command = "podman --version | awk '{print $3}'"
detect_files = "Containerfile", "Dockerfile", "docker-compose.yml", "compose.yml", "podman-compose.yml", "podman-compose.yaml"]
format = "[[via](#52676B) $symbol$output]($style) "



[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[ $duration]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:peach"
format = '[[ ïº $time ](fg:white bg:foam)]($style)'

[env_var]
symbol = "[â•­â•´](bold fg:white)"
variable = 'SHELL'
format = "$symbol"
disabled = false

[line_break]
disabled = false


[character]
disabled = false
success_symbol = '[âœ](bold fg:white)' # âœ â¯
error_symbol = '[âœ˜](bold fg:red)'
# success_symbol = '[â•°â¯ï„…](bold fg:white)'
# error_symbol = '[â•°â¯ï„…](bold fg:red)'
vimcmd_symbol = '[ï´](bold fg:purple)'
vimcmd_replace_one_symbol = '[ï´](bold fg:purple)'
vimcmd_replace_symbol = '[ï´](bold fg:purple)'
vimcmd_visual_symbol = '[ï´](bold fg:lavender)'


#palettes

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "purple"
text = "#111111"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"




[palettes.custom]
sapphire = "#bd93f9"
text = "#bd93f9"
blue = "#89b4fa"
background = "#282a36"
current_line = "#44475a"
foreground = "#111111"
comment = "#6272a4"
cyan = "#8be9fd"
green = '#50fa7b'
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = 'gray'
yellow = "#f1fa8c"


